-- Gerçek danışman listesi faculty-roster.js üzerinden yüklenir.
-- Yönetici hesabı ADMIN_EMAIL / ADMIN_PASSWORD ile database.js içinde oluşturulur.
-- Örnek öğrenci veya danışman hesabı oluşturulmaz.
